# Generated by Django 3.0.8 on 2020-07-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('Published_at', models.DateTimeField(auto_now=True)),
                ('Vacancy', models.IntegerField(default=0)),
                ('Salary', models.IntegerField(default=0)),
            ],
        ),
    ]
